#Plot recent data generated by hsrp_test_9.m
# Invoke from parent directory as
# bash ht9_plt_lp_paths.sh
fname=`octave -q hsrp_test_8.m`
echo ${fname}
PYTHONPATH=$PWD/..:$PWD python ptpath_hsrp_cmp_2.py ${fname}
