#Plot recent data generated by hsrp_test_9.m
# Invoke from parent directory as
# bash ht9_plt.sh
fname=`octave -q hsrp_test_9.m`
echo ${fname}
PYTHONPATH=$PWD/..:$PWD python -m pdb ptpath_pp_groups_test_1.py ${fname}
